
module.exports = {
    USER: 0,
    TRANSACTION: 0,
    USER_TRANSACTION: 0,
    
    EXPENSE_TYPE_EQUAL: "EQUAL",
    EXPENSE_TYPE_EXACT: "EXACT",
    TRANSACTION_TYPE_CREDIT: "CREDIT",
    TRANSACTION_TYPE_DEBIT: "DEBIT"
}